POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "Video 01",
  "description": "Esse é o vídeo 01",
  "duration": 100
}
###
@videoId = 11aebfba-8dbe-4571-bd35-95d10c47a6d4
###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/{{videoId}}
Content-Type: application/json

{
  "title": "Video 04",
  "description": "Esse é o vídeo 02",
  "duration": 200
}

###

DELETE http://localhost:3333/videos/{{videoId}}
