@videoId = 80335b26-c30b-4cb4-991b-953c8880b760
@API_URL_LOCAL = http://localhost:3333
@API_URL_PROD = 
@search = node
###
POST {{API_URL_LOCAL}}/videos
Content-Type: application/json

{
  "title": "Video node",
  "description": "Esse é o vídeo 01",
  "duration": 100
}

###

GET {{API_URL_PROD}}/videos?search={{search}}

###

PUT {{API_URL_LOCAL}}/videos/{{videoId}}
Content-Type: application/json

{
  "title": "Video Node alterado",
  "description": "Esse é o vídeo Node alterado",
  "duration": 200
}

###

DELETE {{API_URL_LOCAL}}/videos/{{videoId}}
