POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "Video node",
  "description": "Esse é o vídeo 01",
  "duration": 100
}

###
@videoId = 90f175c3-0d37-4102-9c38-b8a11db4cbcd
@search = node
###

GET http://localhost:3333/videos?search={{search}}

###

PUT http://localhost:3333/videos/{{videoId}}
Content-Type: application/json

{
  "title": "Video 04",
  "description": "Esse é o vídeo 02",
  "duration": 200
}

###

DELETE http://localhost:3333/videos/{{videoId}}
